# Generated by Django 4.2.6 on 2023-10-29 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='hotels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movnm', models.CharField(max_length=50)),
                ('rldt', models.DateField()),
                ('chart', models.CharField(max_length=50)),
                ('thnm', models.CharField(max_length=50)),
                ('dirnm', models.CharField(max_length=50)),
                ('rat', models.IntegerField()),
            ],
        ),
    ]
