# Generated by Django 4.2.6 on 2023-10-29 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0002_hotels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotels',
            name='rat',
            field=models.BooleanField(),
        ),
    ]
