# Generated by Django 4.2.6 on 2023-10-29 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0003_alter_hotels_rat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotels',
            name='rat',
            field=models.FloatField(),
        ),
    ]
