# Generated by Django 4.2.6 on 2023-10-29 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0007_alter_viewmodel_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='newywmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flightname', models.CharField(max_length=50)),
                ('flightplace', models.CharField(max_length=50)),
                ('flightpicture', models.FileField(upload_to='')),
                ('flightdeparture', models.DateField()),
            ],
        ),
    ]
