# Generated by Django 4.2.6 on 2023-10-29 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0008_newywmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='personmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('phone', models.FloatField()),
            ],
        ),
    ]
