# Generated by Django 4.2.6 on 2023-10-29 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0009_personmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='todosmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emplyeename', models.CharField(max_length=50)),
                ('emplyeelocation', models.CharField(max_length=50)),
                ('employeeprofile', models.FileField(upload_to='')),
                ('employdob', models.DateField()),
            ],
        ),
    ]
